# Generated by Django 4.0.2 on 2022-03-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manufacture',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('storageSize', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('screenSize', models.FloatField()),
                ('manuf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laptop.manuf')),
            ],
            options={
                'db_table': 'laptop',
            },
        ),
    ]
