# Generated by Django 4.0.2 on 2022-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('storageSize', models.IntegerField()),
                ('screenSize', models.FloatField()),
                ('screenResolution', models.CharField(max_length=255)),
                ('ramSize', models.IntegerField()),
                ('connection', models.CharField(max_length=255)),
                ('interfaces', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('frontCamera', models.CharField(max_length=255)),
                ('rearCamera', models.CharField(max_length=255)),
                ('speaker', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mobile',
            },
        ),
    ]
